### ISSUE TITLE
Approachability & Compiled Exe

### ISSUE THREAD

**Issue by arose26** [DavidColson/Polybox#6]
This is a great idea for a fantasy console! However, one of the things that made Pico8 so great was that you just download it and you jump right in even with little knowledge. You open it up and have access to easy editing textures, music, code all right there in the same program. That was great for getting over the initial learning curve.
Granted 3D development is a lot trickier ,but I think at least you could provide a streamlined interface like that. As it stands you don't even offer the compiled exe, when that is standard for most Windows projects on Github. 
I think you could start by offering an exe, as well as example programs, and have them up front on the github. Otherwise, you risk scaring off new users.

**Comment by PixelDough** [comment]
A development environment, and sample games, are in the Planned Features list on the readme.

Right now, it's more comparable to Monogame. A framework to make a game. There is no development environment so there is no compiled exe. You are the one who compiles the exe for your game.

**Comment by Lunastela** [comment]
Would you mind people using it as such? I think the idea of this is really cool, but I'd like to use it for standalone projects or abstract the renderer and render components since I really love the infrastructure of the project. It looks perfect for me, but I'm worried it's going to be tied down to the architecture of the psuedoconsole. If it will be at some point, would you consider creating a framework version or abstracting the renderer as a separate project?

**Comment by DavidColson** [comment]
Sorry, haven't been super responsive due to a new job. But yea the intention is that polybox provides a built in toolset, precompiled, with a scripting language (Polyscript) that lives inside the toolset. The end goal is that you download a packaged executable and you have everything to make games, don't even need a compiler. Of course this will take time, and at the moment I'm focusing on getting polyscript to minimum viable for the project to progress (it is close now)

Right now this is progress toward a promised future, not a usable product.

I have no issue with people using it as a sort of mono-game framework in c++ if you really wish. And I will endeavour to keep the core APIs modular so you can use it as such. Of course the renderer is already suitable for doing this, but you must be comfy using c++ and premake on your own.

**Comment by Atherean1** [comment]
I was looking around the web for something like this and your output results are perfect for my project! Im looking to make a 3D interactive website and would like to use Polybox. The problem is i am an artist, not a programmer and dont know how to use this or if its even possible. Can someone tell me if this would be possible either using Polybox to render or pre render, and where i need to start to learn this so i can use it. Much appreciated!
